version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true
##  برای اینکه Jaeger بتونه داده‌های ردیابی رو به فرمت OpenTelemetry (OTLP) دریافت کنه، باید تنظیم زیر رو فعال کنیم:
